# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# MAGIC %sql
# MAGIC drop table ecomm_dw.silver.dim_customers;
# MAGIC drop table ecomm_dw.silver.dim_orders;
# MAGIC drop table ecomm_dw.silver.dim_products;

# COMMAND ----------

# MAGIC %sql
# MAGIC drop table ecomm_dw.bronze.customers;
# MAGIC drop table ecomm_dw.bronze.orders;
# MAGIC drop table ecomm_dw.bronze.order_items;
# MAGIC drop table ecomm_dw.bronze.products;

# COMMAND ----------

# MAGIC %sql
# MAGIC drop schema ecomm_dw.bronze cascade;
# MAGIC drop schema ecomm_dw.silver cascade;
# MAGIC drop schema ecomm_dw.gold cascade;

# COMMAND ----------

# MAGIC %sql
# MAGIC create schema ecomm_dw.bronze;
# MAGIC create schema ecomm_dw.silver;
# MAGIC create schema ecomm_dw.gold;

# COMMAND ----------

# MAGIC %sql
# MAGIC drop catalog ecomm_dw cascade;

# COMMAND ----------

# MAGIC %sql
# MAGIC create catalog ecomm_dw;

# COMMAND ----------

# MAGIC %sql
# MAGIC drop table ecomm_dw.silver.dim_customers;
# MAGIC drop table ecomm_dw.silver.dim_orders;
# MAGIC drop table ecomm_dw.silver.dim_products;
# MAGIC drop table ecomm_dw.silver.fact_sales;

# COMMAND ----------

# MAGIC %sql
# MAGIC select count(1) from ecomm_dw.silver.dim_orders;